version: "3.9"

services:
    client:
        container_name: client
        image: client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        env_file:
          - ./.env.prod 
          # - CLIENT_PORT=${CLIENT_PORT}
          # - SERVER_PORT=${SERVER_PORT}
    server:
        container_name: server
        image: server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        depends_on:
          - "postgres"
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
            - ./.env.prod
          # SERVER_PORT: ${SERVER_PORT}

    postgres:
      image: postgres:12
      restart: always 
      ports:
        - "${POSTGRES_PORT}:5432"
      env_file:
        - ./.env.prod 
      # environment:
      #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #   POSTGRES_USER: ${POSTGRES_USER}
      #   POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

